name: Build & Deploy (cron)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Unzip the AutoAffiliate bundle into a working directory; prefer fixed zip but fallback to original
      - name: Unzip bundle
        run: |
          if [ -f AutoAffiliate_Lite_fixed.zip ]; then
            unzip -o AutoAffiliate_Lite_fixed.zip -d site
          else
            unzip -o AutoAffiliate_Lite.zip -d site
          fi

      # Install required Python dependencies from the extracted bundle
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r site/requirements.txt

      # Build the static site using the provided script
      - name: Build site
        env:
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }}
        run: |
          cd site
          python scripts/generate.py --base-url "$SITE_BASE_URL"

      # Copy the generated site to the root for GitHub Pages
      - name: Copy site
        run: |
          rm -rf docs
          mv site/docs docs
